#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Characterization tests pinning the numerical behavior of Kinisot v2.0.2.

Golden values were generated by running the current code and cross-checked
against the reference outputs shipped in kinisot/examples/gaussian/
(claisen_kinisot.dat, tetramethylcyclohexane_kinisot.dat, comparison.dat),
which they match to all printed digits.
"""

import pytest
from kinisot import Kinisot
from conftest import datapath

REL = 1e-6


def run_kie(reactants, ts, prd, iso, temperature, scaling, freq_cutoff=50.0):
    rct = [datapath(p) for p in reactants]
    ts = [datapath(p) for p in ts] if ts else None
    prd = [datapath(p) for p in prd] if prd else None
    return Kinisot.compute_isotope_effect(rct, ts, prd, iso, temperature, scaling, freq_cutoff)


# Columns: name, reactants, ts, prd, iso labels (one per file), T/K, scale factor,
#          V-ratio, ZPE, EXC, TRPF, KIE, 1D-tunn, corr-KIE
CASES = [
    # Claisen rearrangement, 13C/2H KIEs at 393 K with 0.961 scaling
    ("claisen_C5_393K", ['gaussian/claisen_gs.out'], ['gaussian/claisen_ts.out'], None,
     ['5', '5'], 393.0, 0.961,
     1.000175989, 0.999077108, 1.000680416, 1.001962438, 1.001895148, 1.000044477, 1.001939709),
    ("claisen_C4_393K", ['gaussian/claisen_gs.out'], ['gaussian/claisen_ts.out'], None,
     ['4', '4'], 393.0, 0.961,
     1.012716215, 1.036594528, 1.001969436, 0.978988748, 1.029743004, 1.003157113, 1.032994019),
    ("claisen_H78_393K", ['gaussian/claisen_gs.out'], ['gaussian/claisen_ts.out'], None,
     ['7,8', '7,8'], 393.0, 0.961,
     1.007258229, 0.885604875, 1.063923543, 1.006138148, 0.954880133, 1.001815967, 0.956614164),
    # Same substitution, different temperature and no scaling
    ("claisen_C5_298K_unscaled", ['gaussian/claisen_gs.out'], ['gaussian/claisen_ts.out'], None,
     ['5', '5'], 298.15, 1.0,
     1.000175989, 0.998734358, 1.001118967, 1.001962438, 1.001990364, 1.000087841, 1.002078380),
    # Diels-Alder with two separate reactant files
    ("DA_multi_rct_C19", ['gaussian/dienophile.out', 'gaussian/diene.out'], ['gaussian/DATS.out'], None,
     ['0', '10', '19'], 298.15, 0.963,
     1.000072559, 0.995775373, 0.981489653, 1.023884832, 1.000759513, 1.000027859, 1.000787393),
    ("DA_multi_rct_C15", ['gaussian/dienophile.out', 'gaussian/diene.out'], ['gaussian/DATS.out'], None,
     ['0', '6', '15'], 298.15, 0.963,
     1.009797738, 1.001688178, 0.986483873, 1.020845417, 1.018631061, 1.003711569, 1.022411780),
    # Same TS carbon via the pre-formed reactant complex (single reactant file)
    ("DA_single_rct_C15", ['gaussian/DATS_rct.out'], ['gaussian/DATS.out'], None,
     ['15', '15'], 298.15, 0.963,
     1.009797738, 1.003033205, 1.012514295, 0.992401183, 1.017743039, 1.003711569, 1.021520462),
    # Equilibrium isotope effect (--prd path): CD3 axial/equatorial preference
    ("EQE_tmch_290K", ['gaussian/tetramethylcyclohexane.out'], None, ['gaussian/tetramethylcyclohexane.out'],
     ['24,25,26', '28,29,30'], 290.0, 1.0,
     1.000000000, 1.027782953, 1.025380928, 0.985373194, 1.038454300, 1.000000000, 1.038454300),
    ("EQE_tmch_300K", ['gaussian/tetramethylcyclohexane.out'], None, ['gaussian/tetramethylcyclohexane.out'],
     ['24,25,26', '28,29,30'], 300.0, 1.0,
     1.000000000, 1.026844535, 1.025140026, 0.985373194, 1.037262389, 1.000000000, 1.037262389),
]


@pytest.mark.parametrize(
    "name, reactants, ts, prd, iso, temperature, scaling, vratio, ZPE, EXC, TRPF, KIE, tunn, corrKIE",
    CASES, ids=[c[0] for c in CASES])
def test_isotope_effect(name, reactants, ts, prd, iso, temperature, scaling,
                        vratio, ZPE, EXC, TRPF, KIE, tunn, corrKIE):
    (rpfrs, zpe_val, exc_val, trpf_val, kie_val, corr_kie_val,
     tunn_corr_val, freq_fac) = run_kie(reactants, ts, prd, iso, temperature, scaling)
    assert freq_fac == pytest.approx(vratio, rel=REL)
    assert zpe_val == pytest.approx(ZPE, rel=REL)
    assert exc_val == pytest.approx(EXC, rel=REL)
    assert trpf_val == pytest.approx(TRPF, rel=REL)
    assert kie_val == pytest.approx(KIE, rel=REL)
    assert tunn_corr_val == pytest.approx(tunn, rel=REL)
    assert corr_kie_val == pytest.approx(corrKIE, rel=REL)


def test_ts_imaginary_frequency_detected():
    # The uphill TS mode of the Claisen TS at 0.961 scaling, from claisen_kinisot.dat
    rpfrs, *_ = run_kie(['gaussian/claisen_gs.out'], ['gaussian/claisen_ts.out'], None,
                        ['5', '5'], 393.0, 0.961)
    assert rpfrs[2].im_frequency_wn == pytest.approx(463.9, abs=0.05)
    assert not hasattr(rpfrs[0], "im_frequency_wn")  # ground state has none
